# Generated by Django 4.1.3 on 2022-11-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='availableSources',
            new_name='availableResources',
        ),
    ]
