# Generated by Django 4.1.3 on 2022-11-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0005_alter_availableresources_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, unique=True)),
                ('resource', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='availableResources',
        ),
    ]
