# Generated by Django 4.1.3 on 2022-11-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0007_articles_datepublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='fake_votes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='non_fake_votes',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
