# Generated by Django 4.1.3 on 2022-11-20 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('migrations', '0008_articles_fake_votes_articles_non_fake_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='datePublished',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
